<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>DivisiBillWsClient</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>preview</LangVersion>
		<UseMaterial3>true</UseMaterial3>

		<!--Suppress NU1608 warnings for AndroidX package version mismatches - these are resolved correctly by NuGet-->
		<NoWarn>$(NoWarn);NU1608</NoWarn>

		<!-- Display name -->
		<ApplicationTitle>DivisiBillWsClient</ApplicationTitle>

		<!-- App Identifier IMPERSONATES DIVISIBILL -->
		<ApplicationId>com.autoplus.divisibill</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">34.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.90" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />
		<PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
	</ItemGroup>

	<!--Add In-App Billing package, but only for Android-->
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
	  <PackageReference Include="Xamarin.Android.Google.BillingClient">
	    <Version>9.1.0.1</Version>
	  </PackageReference>
	</ItemGroup>

	<!--Generate the file holding the build secrets on every build-->
	<!--First get the secrets from environment variables-->

	<PropertyGroup Condition="'$(Configuration)|$(TargetOsPlatform)' == 'debug|android'">
		<DivisiBillWsUri Condition="'$(DivisiBillWsUri)' == ''">$(DIVISIBILL_WS_URI_DEBUGA)</DivisiBillWsUri>
		<DivisiBillWsKey Condition="'$(DivisiBillWsKey)' == ''">$(DIVISIBILL_WS_KEY_DEBUGA)</DivisiBillWsKey>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetOsPlatform)' == 'debug|windows'">
		<DivisiBillWsUri Condition="'$(DivisiBillWsUri)' == ''">$(DIVISIBILL_WS_URI_DEBUGW)</DivisiBillWsUri>
		<DivisiBillWsKey Condition="'$(DivisiBillWsKey)' == ''">$(DIVISIBILL_WS_KEY_DEBUGW)</DivisiBillWsKey>
	</PropertyGroup>

	<PropertyGroup>
		<!--If nothing has been recognized so far just use the released configuration-->
		<DivisiBillWsUri Condition="'$(DivisiBillWsUri)' == ''">$(DIVISIBILL_WS_URI)</DivisiBillWsUri>
		<DivisiBillWsKey Condition="'$(DivisiBillWsKey)' == ''">$(DIVISIBILL_WS_KEY)</DivisiBillWsKey>
		<BuildInfoText>
			<![CDATA[
// <auto-generated/>
// THIS FILE IS GENERATED BY EACH BUILD - DO NOT EDIT IT
namespace DivisiBillWsClient.Generated
{
	internal class BuildInfo
	{
		internal const string DivisiBillWsUri = "$(DivisiBillWsUri)"%3b
		internal const string DivisiBillWsKey = "$(DivisiBillWsKey)"%3b
		internal const string DivisiBillWsUriNgrok = "$(DIVISIBILL_WS_URI_NGROK)"%3b
		internal const string DivisiBillWsProductionConnectionStringB64 = "$(DIVISIBILL_WS_PRODUCTIONCONNECTIONSTRINGB64)"%3b
		internal const string DivisiBillWsAlternateConnectionStringB64 = "$(DIVISIBILL_WS_ALTERNATECONNECTIONSTRINGB64)"%3b
		internal const string DivisiBillTestProJsonB64 = "$(DIVISIBILL_TEST_PRO_JSON_B64)"%3b
		internal const string DivisiBillTestOcrJsonB64 = "$(DIVISIBILL_TEST_OCR_JSON_B64)"%3b
		internal const string DivisiBillTestProSignatureB64 = "$(DIVISIBILL_TEST_PRO_SIGNATURE_B64)"%3b
		internal const string DivisiBillTestOcrSignatureB64 = "$(DIVISIBILL_TEST_OCR_SIGNATURE_B64)"%3b
	}
}
]]>
		</BuildInfoText>
	</PropertyGroup>

	<Target Name="AddBuildInfo" Inputs="$(MSBuildAllProjects)" BeforeTargets="BeforeBuild;CoreCompile" Outputs="ForceBuildEveryTime">
		<Message Text="AddBuildInfo was invoked for file $(BuildInfoFilePath)" Importance="low" />
		<PropertyGroup>
			<BuildInfoFilePath>$(IntermediateOutputPath)BuildGenerated\BuildInfo.g.cs</BuildInfoFilePath>
		</PropertyGroup>
		<ItemGroup>
			<Compile Include="$(BuildInfoFilePath)" />
			<FileWrites Include="$(BuildInfoFilePath)" />
		</ItemGroup>
		<WriteLinesToFile Lines="$(BuildInfoText)" File="$(BuildInfoFilePath)" Overwrite="true" />
	</Target>
	<!--End file generation-->

	<!--Generate the file holding the build timestamp, this changes on every build-->
	<PropertyGroup>
		<Today>$([System.DateTime]::UtcNow.ToString("O"))</Today>
		<BuildEnvironmentText>
			<![CDATA[
// <auto-generated/>
// THIS FILE IS GENERATED BY EACH BUILD - DO NOT EDIT IT
namespace DivisiBillWsClient.Generated
{
    internal static class BuildEnvironment
    {
        internal const string BuildTimeString = "$(Today)"%3b
    }
}
]]>
		</BuildEnvironmentText>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.19041.0|AnyCPU'" />

	<Target Name="AddBuildEnvironment" BeforeTargets="BeforeBuild;CoreCompile" Inputs="$(MSBuildAllProjects)" Outputs="ForceBuildEveryTime">
		<Message Text="AddBuildEnvironment was invoked for file $(BuildInfoFilePath)" Importance="low" />
		<PropertyGroup>
			<BuildEnvironmentFilePath>$(IntermediateOutputPath)BuildGenerated\BuildEnvironment.g.cs</BuildEnvironmentFilePath>
		</PropertyGroup>
		<ItemGroup>
			<Compile Include="$(BuildEnvironmentFilePath)" />
			<FileWrites Include="$(BuildEnvironmentFilePath)" />
		</ItemGroup>
		<WriteLinesToFile Lines="$(BuildEnvironmentText)" File="$(BuildEnvironmentFilePath)" Overwrite="true" />
	</Target>
	<!--End file generation-->

</Project>
